### ISSUE TITLE
Elixir 1.8 test is running Elixir 1.7

### ISSUE THREAD

**Issue by garthk** [opencensus-beam/opencensus_absinthe#24]
```yml
  testing:
    jobs:
      - test:
          name: "Elixir 1.8"
          elixir_version: "1.7"
```
Oops.
